/**
 * Image URL lookup from pre-built cache.
 * `data/image-cache.json` is generated by `npm run fetch-images`
 * using Pexels (primary) + Unsplash (fallback).
 * No API calls happen at runtime — all URLs are baked in at build time.
 */
import imageCache from "@/../data/image-cache.json";
import ogManifest from "@/../data/og-manifest.json";

const cache = imageCache as Record<string, string>;
const ogSlugs = new Set(ogManifest as string[]);

const sizeDims: Record<string, string> = {
  sm: "h=400&w=400",
  md: "h=500&w=700",
  lg: "h=650&w=940",
  og: "h=630&w=1200",
};

/**
 * Returns the cached image URL for a given item slug,
 * or null if no image is available.
 *
 * Returning null (instead of a broken external URL) lets the
 * ItemImage component render a CSS gradient placeholder
 * immediately — no flash of broken image, no failed requests.
 *
 * Appends &fm=webp for modern format support (both Pexels and
 * Unsplash serve WebP when requested, ~30-50% smaller than JPEG).
 */
export function getItemImageUrl(
  slug: string,
  width = 600,
  height = 400,
  size: "sm" | "md" | "lg" | "og" = "md"
): string | null {
  const url = cache[slug];
  if (!url) return null;

  let sized = url.replace(/h=\d+&w=\d+/, sizeDims[size]);

  // Request WebP format for smaller payloads
  if (!sized.includes("fm=webp")) {
    sized = sized.replace(/fm=jpg/, "fm=webp");
  }

  return sized;
}

/** Check if an image URL came from Pexels (for attribution) */
export function isPexelsImage(slug: string): boolean {
  const url = cache[slug];
  if (!url) return false;
  try {
    const host = new URL(url).hostname;
    return host === "images.pexels.com" || host.endsWith(".pexels.com");
  } catch {
    return false;
  }
}

/** Check whether a slug has a cached image */
export function hasImage(slug: string): boolean {
  return !!cache[slug];
}

/**
 * Returns the per-item OG PNG URL if one was generated by
 * `scripts/generate-og-images.mjs`. The generator produces a PNG
 * for every slug that has a cached image, so we mirror that check.
 * Returns null when the caller should fall back to getItemImageUrl.
 */
export function getOgImageUrl(slug: string): string | null {
  return ogSlugs.has(slug) ? `/og/${slug}.png` : null;
}
