/**
 * Image URL lookup from pre-built cache.
 * `data/image-cache.json` is generated by `npm run fetch-images`
 * using Pexels (primary) + Unsplash (fallback).
 * No API calls happen at runtime — all URLs are baked in at build time.
 */
import imageCache from "@/../data/image-cache.json";

const cache = imageCache as Record<string, string>;

/** Picsum fallback for slugs missing from the cache */
function picsum(slug: string, w: number, h: number): string {
  return `https://picsum.photos/seed/${slug}/${w}/${h}`;
}

const sizeDims: Record<string, string> = {
  sm: "h=400&w=400",
  md: "h=500&w=700",
  lg: "h=650&w=940",
};

export function getItemImageUrl(
  slug: string,
  width = 600,
  height = 400,
  size: "sm" | "md" | "lg" = "md"
): string {
  const url = cache[slug];
  if (!url) return picsum(slug, width, height);
  return url.replace(/h=\d+&w=\d+/, sizeDims[size]);
}

/** Check if an image URL came from Pexels (for attribution) */
export function isPexelsImage(slug: string): boolean {
  return (cache[slug] || "").includes("pexels.com");
}
