/**
 * Image URL lookup from pre-built cache.
 * `data/image-cache.json` is generated by `npm run fetch-images`
 * using Pexels (primary) + Unsplash (fallback).
 * No API calls happen at runtime — all URLs are baked in at build time.
 */
import imageCache from "@/../data/image-cache.json";

const cache = imageCache as Record<string, string>;

const sizeDims: Record<string, string> = {
  sm: "h=400&w=400",
  md: "h=500&w=700",
  lg: "h=650&w=940",
  og: "h=630&w=1200",
};

/**
 * Returns the cached image URL for a given item slug,
 * or null if no image is available.
 *
 * Returning null (instead of a broken external URL) lets the
 * ItemImage component render a CSS gradient placeholder
 * immediately — no flash of broken image, no failed requests.
 *
 * Appends &fm=webp for modern format support (both Pexels and
 * Unsplash serve WebP when requested, ~30-50% smaller than JPEG).
 */
export function getItemImageUrl(
  slug: string,
  width = 600,
  height = 400,
  size: "sm" | "md" | "lg" | "og" = "md"
): string | null {
  const url = cache[slug];
  if (!url) return null;

  let sized = url.replace(/h=\d+&w=\d+/, sizeDims[size]);

  // Request WebP format for smaller payloads
  if (!sized.includes("fm=webp")) {
    sized = sized.replace(/fm=jpg/, "fm=webp");
  }

  return sized;
}

/**
 * Build a `srcset` of multiple widths from a single cached URL.
 *
 * Pexels and Unsplash both honour their query-param sizing endpoints
 * (`?w=…&h=…`), so we can rewrite a single cached URL into a few
 * resolution variants without re-fetching from the source.
 *
 * Returns null when the slug has no cached image — caller should fall
 * back to its placeholder.
 */
export function getItemImageSrcSet(
  slug: string,
  widths: number[] = [400, 700, 940, 1200]
): { srcSet: string; defaultSrc: string } | null {
  const url = cache[slug];
  if (!url) return null;

  const buildVariant = (w: number) => {
    // Approximate height assuming 16/10 aspect (matches default ItemImage layout)
    const h = Math.round((w * 10) / 16);
    let sized = url.replace(/h=\d+&w=\d+/, `h=${h}&w=${w}`);
    if (!sized.includes("fm=webp")) sized = sized.replace(/fm=jpg/, "fm=webp");
    return { url: sized, w };
  };

  const variants = widths.map(buildVariant);
  return {
    srcSet: variants.map((v) => `${v.url} ${v.w}w`).join(", "),
    defaultSrc: variants[Math.min(2, variants.length - 1)].url,
  };
}

/** Check if an image URL came from Pexels (for attribution) */
export function isPexelsImage(slug: string): boolean {
  const url = cache[slug];
  if (!url) return false;
  try {
    const host = new URL(url).hostname;
    return host === "images.pexels.com" || host.endsWith(".pexels.com");
  } catch {
    return false;
  }
}

/** Check whether a slug has a cached image */
export function hasImage(slug: string): boolean {
  return !!cache[slug];
}
